FROM ubuntu:18.04
MAINTAINER  Harsh-Singh
RUN apt update -y && apt install apache2 -y
RUN echo Hello Apache server on Ubuntu Docker Container > /var/www/html/index.html
##CMD /usr/sbin/apache2ctl -D FOREGROUND
CMD [ "apache2ctl", "-DFOREGROUND" ]

